name: Go
on:
  pull_request: 
    branches:
      - main
      - v*
jobs:
  go:
    name: "CI for SDK"
    steps:
      - name: Set up Go 1.19.2
        uses: actions/setup-go@v1
        with:
          go-version: 1.19.2
        id: go
      
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Cache Go Modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Test
        run: go test ./...
          
      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.52.2
          sudo cp ./bin/golangci-lint $GOPATH/bin/
          golangci-lint run -E revive --timeout 600s ./...